typography_spectrum: 0.45536782359704375
color:
  brandColors: []
  brandStrength: 0.25949362269602716
  lightness: 0.06751065794378519
  saturation: 0.6132258686702698
  rhythmicContrast: 0.26444927346892655
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.45507952896878123
analytics:
  google: null
  facebook: null
  twitter: null
name: appliant
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: TI
purpose: []
